FROM node:20-alpine AS builder

WORKDIR /usr/src/app

RUN npm install -g pnpm@10.11.0

COPY ./packages ./packages
COPY ./apps/server ./apps/server
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

RUN pnpm install 
RUN pnpm build

EXPOSE 3000
ENV NODE_ENV=production

CMD ["pnpm", "start:server"]
