name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.server
          push: true
          tags: callmeashu/codemate-backend:${{github.sha}}
          
      - name: Deploy to VM
        run: |
          echo "${{ secrets.VM_ACCESS_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.233.9.91 \
          -t "
          sudo docker stop user_backend || true && \
          sudo docker rm user_backend || true && \

          IMAGE_ID=\$(sudo docker images callmeashu/codemate-backend --format '{{.ID}}') && \
          if [ ! -z \"\$IMAGE_ID\" ]; then sudo docker rmi -f \$IMAGE_ID; fi && \

          sudo docker run --name user_backend -d \
              -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
              -e JWT_ACCESS_TOKEN_SECRET='${{ secrets.JWT_ACCESS_TOKEN_SECRET }}' \
              -e JWT_REFRESH_TOKEN_SECRET='${{ secrets.JWT_REFRESH_TOKEN_SECRET }}' \
              -e JUDGE0_API_KEY='${{ secrets.JUDGE0_API_KEY }}' \
              -p 3000:3000 \
              callmeashu/codemate-backend:${{ github.sha }}
          "

