name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Build the docker image
        # Push docker image to docker hub
      - name: Build and push image to docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.server
          push: true
          tags: callmeashu/codemate-backend:${{github.sha}}
# SSH into our VM and start the new image
