name: Deploy Frontend
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.client
          push: true
          tags: callmeashu/codemate-frontend:${{github.sha}}
          build-args: |
            VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}
            VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}

      - name: Deploy to VM
        run: |
          echo "${{ secrets.VM_ACCESS_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.234.77.65 -t "

          sudo docker stop user_frontend || true && \
          sudo docker rm user_frontend || true && \

          IMAGE_ID=\$(sudo docker images callmeashu/codemate-frontend --format '{{.ID}}') && \
          if [ ! -z \"\$IMAGE_ID\" ]; then sudo docker rmi -f \$IMAGE_ID; fi && \

          sudo docker run --name user_frontend -d \
          -p 5173:80 \
          callmeashu/codemate-frontend:${{ github.sha }}"
