name: Deploy Websockets
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.websockets
          push: true
          tags: callmeashu/codemate-socketserver:${{github.sha}}
      - name: Deploy to VM
        run: |
           echo "${{ secrets.VM_ACCESS_KEY }}" > ~/ssh_key
            chmod 700 ~/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.233.9.91 -t "

            sudo docker stop user_socketserver || true && \
            sudo docker rm user_socketserver || true && \

            IMAGE_ID=\$(sudo docker images callmeashu/codemate-socketserver --format '{{.ID}}') && \
            if [ ! -z \"\$IMAGE_ID\" ]; then sudo docker rmi -f \$IMAGE_ID; fi && \

            sudo docker run --name user_socketserver -d \
                -e REDIS_USERNAME='${{ secrets.REDIS_USERNAME }}' \
                -e REDIS_PASSWORD='${{ secrets.REDIS_PASSWORD }}' \
                -e REDIS_HOST='${{ secrets.REDIS_HOST }}' \
                -e REDIS_PORT='${{ secrets.REDIS_PORT }}' \
                -p 8080:8080 \
                callmeashu/codemate-socketserver:${{ github.sha }}
            "